//THIS FILE IS AUTOGENERATED, DO NOT EDIT
use worker::{Context, Env, Request, Response, Result, Router};

#[path = "pages"]
pub mod pages {
    pub mod test;
}

pub async fn router(req: Request, env: Env) -> Result<Response> {
    let router = Router::new();

    return router.on_async("/", pages::test::test).run(req, env).await;
}
